version: '3.3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - db
      
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql

volumes:
  my-db:
